name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login DockerHub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aplicaciones9/cicd-pipeline:latest
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Pull Docker Image"
        run: docker pull aplicaciones9/cicd-pipeline:latest
      - name: "Delete Old Docker Container"
        run: sudo docker rm -f cicd-pipeline-container || true
      - name: "Run Docker Container"
        run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container aplicaciones9/cicd-pipeline
